spring:
  application:
    name: api

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#   * h2 콜솔 *
#    h2:
#      console:
#        enabled: true
#        path: /h2-console

#  * h2 *
#    datasource:
#      url: jdbc:h2:tcp://localhost/~/payment
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver

#  * mysql *
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
